### ISSUE TITLE
Add EventListenerException

### ISSUE THREAD

**Issue by ronakmistry36** [points-log/pl-oss#24]
Any thought on this feature? @venusvavadiya @shailscript

**Comment by venusvavadiya** [comment]
We followed the YAGNI while creating Exceptions. We can surely add this when we need it. I am thinking about removing `CommandHandlerException` as I do not see the use. #25.

Let me know what you guys think.

**Comment by shailscript** [comment]
Following YAGNI we should. We can always add it when necessary.

**Comment by ronakmistry36** [comment]
Thats good we all are on same page 💪 😃
