### ISSUE TITLE
Test sequence of event for apply method in AggregateRepository

### ISSUE THREAD

**Issue by venusvavadiya** [points-log/pl-oss#27]
We want to test that apply method is called in sequence for the events. We have tested the same in [here](https://github.com/points-log/pl-oss/blob/6508a12a8c01a5178db6160913fd263d2c0c9eb4/libs/adapter/src/lib/event-store-db/event-store-db.event-subscription.spec.ts#L52).

**NOTE**
We do not need a generator function here since we are simply using the `forEach` unlike the async iterable.

**Comment by ronakmistry36** [comment]
@venusvavadiya [code](https://github.com/points-log/pl-oss/blob/main/libs/domain-core/src/lib/aggregate-repository.spec.ts#L61) - looks like it's already implemented that way, if I am wrong please help me to recall the approach.

**Comment by venusvavadiya** [comment]
@ronakmistry36 I think we decided to add one more event and test the sequence.
